# Generated by Django 4.2.5 on 2023-09-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='upload',
            field=models.URLField(blank=True, default=''),
        ),
    ]
